# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

callViaXPtr <- function(x, xpsexp) {
    .Call('Rdtq_callViaXPtr', PACKAGE = 'Rdtq', x, xpsexp)
}

#' Density Tracking by Quadrature (DTQ)
#'
#' \code{rdtq} implements a DTQ algorithm to compute the probability density
#' function (PDF) of a stochastic differential equation (SDE) with
#' user-specified drift and diffusion functions. The SDE can be written as:
#'
#' \deqn{ dX(t) = f(X(t)) dt + g(X(t)) dW(t) }
#'
#' where \eqn{W(t)} is standard Brownian motion, \eqn{f} is the drift
#' function, and \eqn{g} is the diffusion function. If we let \eqn{p(x,t)}
#' denote the time-dependent PDF of \eqn{X(t)}, then \code{rdtq} computes
#' \eqn{p(x,T)} for a fixed time \eqn{T}.
#'
#' Note that the PDF is computed on a spatial grid that can be specified in
#' one of three ways:
#' \enumerate{
#'  \item Specify a real, positive value \eqn{k} and a positive integer
#' \eqn{M} = \code{bigm}. In this case, the PDF will be computed on the grid
#' \eqn{x_j = j k} where \eqn{j = -M, -M+1, ..., M-1, M}. In total,
#' there will be \eqn{2M+1} grid points.
#'  \item Specify a real, positive integer \eqn{M} and a computational domain
#' \eqn{[a,b]}. In this case, there will be exactly \eqn{M} equispaced grid
#' points. The grid spacing will be \eqn{k = (b-a)/(M-1)}.
#'  \item Specify the entire spatial grid via \code{xvec}.
#' }
#'
#' @param h Time step size, a positive numeric scalar.
#' @param k Spatial grid spacing, a positive numeric scalar.
#' @param bigm A positive integer such that -\code{bigm*k} and \code{bigm*k}
#' are, respectively, the minimum and maximum grid points.
#' @param x0 A numeric scalar indicating a fixed initial condition of the
#'   form \eqn{X(0)}=\code{x0}.
#' @param T The final time, a positive numeric scalar. The computation
#'   assumes an initial time of \eqn{t}=0 and then computes the PDF at time
#'   \eqn{t}=\code{T}.
#' @param drift A pointer to the drift function.
#' @param diffusion A pointer to the diffusion function.
#' @return The output consists of a list with two elements:
#' \describe{
#'   \item{\code{xvec}}{a numeric vector that contains the spatial grid}
#'   \item{\code{pdf}}{a numeric vector that contains the PDF evaluated at the grid points}
#' }
#'
rdtq <- function(h, k, bigm, x0, T, drift, diffusion) {
    .Call('Rdtq_rdtq', PACKAGE = 'Rdtq', h, k, bigm, x0, T, drift, diffusion)
}

